version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y git openssh-client
  build:
    commands:
      - echo "Deploying to EC2..."
      - scp -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa -r ./ ubuntu@$EC2_IP:/home/ubuntu/app
      - ssh -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa ubuntu@$EC2_IP "bash /home/ubuntu/deploy.sh"
