version: 0.2

phases:
  install:
    commands:
      - echo "✅ Installing SSH tools..."
      - apt-get update && apt-get install -y unzip openssh-client

  pre_build:
    commands:
      - echo "🔐 Decoding SSH private key..."
      - echo "$DEPLOY_KEY_BASE64" | base64 -d > deploy_key.pem
      - chmod 600 deploy_key.pem
      - echo "🔐 Adding server IP to known_hosts..."
      - ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts

  build:
    commands:
      - echo "📤 Sending files to EC2..."
      - scp -i deploy_key.pem -r ./index.html ubuntu@$SERVER_IP:/var/www/html/

  post_build:
    commands:
      - echo "🚀 Deployment complete!"
      - ssh -i deploy_key.pem ubuntu@$SERVER_IP "sudo systemctl restart apache2"
